### ISSUE TITLE
How to specify a template file extension?

### ISSUE THREAD

**Issue by remnev** [express-bem/bh#1]
Hi!

For example, I have two separately kinds of templates. There are the server-side templates `demo.server.bh.js` and the client-side `demo.browser.bh.js`. How to specify any custom file extension (`server.bh.js` in this case) to the render processor?

My test example:

``` js
var express = require('express');
var app = express();
var ExpressBem = require('express-bem');
var bem = ExpressBem({
        root: '.',
        path: './bundles'
    }).bindTo(app);

bem.usePlugin('express-bem-bh');

app.get('/', function (req, res) {
    res.render('demo', {bemjson: {block: 'root'}});
});

app.listen(3000);
```

**Comment by qfox** [comment]
@remnev At first you can pass full path `'demo.server.bh.js'` or `'demo.server'`

Also you can use engine with another `extension`:

``` js
bem.engine('.server.bh.js', require('express-bem-bh/lib/engines/bh'));
```

or do a trick:

``` js
bem.engine('.server.bh.js', function (name, options, cb) {
    this.thru('bh');
});
bem.usePlugin('express-bem-bh');
```

p.s. You can see all possible engine declaration cases in readme:
https://github.com/express-bem/express-bem#engine

Thanks for the question ;-)

**Comment by remnev** [comment]
Nice!
I enjoyed this:

``` js
expressBem.bindTo(app);
expressBem.engine('.server.bh.js', require('express-bem-bh/lib/engines/bh'));
```
